In [ ]:
import pandas as pd

In [ ]:
country = pd.read_csv("/content/detailed_country_job_info.csv")

In [ ]:
careerbliss = pd.read_csv("/content/careerbliss_reviews_fixed.csv")

In [ ]:
country

,국가,대륙,주요 산업,비자 유형,평균 임금 수준,최저임금(USD/월),소득세율(%),유망 업종,취업 가능성,언어 요구사항
0,일본,아시아,제조업/IT,H-1,중간,1200,20,IT/제조업,높음,일본어
1,미국,북미,IT/금융,H-1B,높음,2000,25,AI/소프트웨어,중간,영어
2,캐나다,북미,자원/서비스,Express Entry,중간,1800,22,에너지/IT,높음,영어
3,호주,대양주,광업/교육,Temporary Skill Shortage,중간,2500,30,헬스케어/광업,높음,영어
4,뉴질랜드,대양주,농업/관광,Essential Skills,중간,2300,28,농업/친환경산업,중간,영어
5,대만,아시아,전자/반도체,Employment Gold Card,중간,1500,18,반도체/IT,높음,중국어/영어
6,말레이시아,아시아,제조/서비스,Employment Pass,낮음,900,15,전자/물류,중간,영어
7,미얀마,아시아,농업/제조,Business Visa,낮음,300,10,섬유/농업,낮음,영어/현지어
8,베트남,아시아,제조/IT,Business Visa,낮음,400,12,IT/소비재,중간,영어/베트남어
9,싱가포르,아시아,금융/무역,Employment Pass,높음,2200,17,핀테크/바이오,높음,영어
10,인도,아시아,IT/제조,Employment Visa,낮음,200,10,IT/소프트웨어,중간,영어
11,인도네시아,아시아,자원/제조,Work Permit,낮음,300,10,자원개발/건설,중간,영어/인도네시아어
12,중국,아시아,제조/IT,Z Visa,중간,600,20,AI/반도체,중간,중국어
13,캄보디아,아시아,농업/관광,E Visa,낮음,200,10,농업/건설,낮음,영어/크메르어
14,태국,아시아,관광/제조,Non-Immigrant B,낮음,300,12,관광/요식업,중간,영어/태국어
15,필리핀,아시아,BPO/관광,9(G) Visa,낮음,250,8,BPO/게임,중간,영어/타갈로그어
16,홍콩,아시아,금융/무역,Employment Visa,높음,2300,15,금융/국제무역,높음,영어/중국어
17,네덜란드,유럽,물류/에너지,Highly Skilled Migrant,높음,2800,35,해운/로지스틱스,높음,네덜란드어/영어
18,독일,유럽,자동차/엔지니어링,EU Blue Card,높음,3200,40,자동차/로봇,높음,독일어/영어
19,러시아,유럽,에너지/자원,Work Visa,중간,600,13,에너지/광산,중간,러시아어
20,스웨덴,유럽,IT/제조,Work Permit,높음,3100,32,IT/게임,높음,스웨덴어/영어
21,영국,유럽,금융/교육,Skilled Worker,높음,2800,40,금융/헬스케어,높음,영어
22,헝가리,유럽,제조/IT,EU Blue Card,중간,1400,19,IT/제조업,중간,헝가리어/영어
23,폴란드,유럽,제조/IT,National Visa,중간,1300,17,반도체/로봇,중간,폴란드어/영어
24,핀란드,유럽,IT/에너지,Residence Permit,높음,3200,35,AI/바이오,높음,핀란드어/영어
25,아랍에미리트,중동,석유/건설,Employment Visa,높음,2500,0,에너지/부동산,높음,영어/아랍어
26,멕시코,중남미,제조/자동차,Temporary Resident,낮음,500,10,자동차/가공업,낮음,스페인어
27,브라질,중남미,에너지/농업,Work Visa,낮음,400,7,농업/제약,중간,포르투갈어

In [ ]:
country2 = country.sort_values(by='최저임금(USD/월)', ascending=False)

country2

,국가,대륙,주요 산업,비자 유형,평균 임금 수준,최저임금(USD/월),소득세율(%),유망 업종,취업 가능성,언어 요구사항
24,핀란드,유럽,IT/에너지,Residence Permit,높음,3200,35,AI/바이오,높음,핀란드어/영어
18,독일,유럽,자동차/엔지니어링,EU Blue Card,높음,3200,40,자동차/로봇,높음,독일어/영어
20,스웨덴,유럽,IT/제조,Work Permit,높음,3100,32,IT/게임,높음,스웨덴어/영어
17,네덜란드,유럽,물류/에너지,Highly Skilled Migrant,높음,2800,35,해운/로지스틱스,높음,네덜란드어/영어
21,영국,유럽,금융/교육,Skilled Worker,높음,2800,40,금융/헬스케어,높음,영어
3,호주,대양주,광업/교육,Temporary Skill Shortage,중간,2500,30,헬스케어/광업,높음,영어
25,아랍에미리트,중동,석유/건설,Employment Visa,높음,2500,0,에너지/부동산,높음,영어/아랍어
16,홍콩,아시아,금융/무역,Employment Visa,높음,2300,15,금융/국제무역,높음,영어/중국어
4,뉴질랜드,대양주,농업/관광,Essential Skills,중간,2300,28,농업/친환경산업,중간,영어
9,싱가포르,아시아,금융/무역,Employment Pass,높음,2200,17,핀테크/바이오,높음,영어
1,미국,북미,IT/금융,H-1B,높음,2000,25,AI/소프트웨어,중간,영어
2,캐나다,북미,자원/서비스,Express Entry,중간,1800,22,에너지/IT,높음,영어
5,대만,아시아,전자/반도체,Employment Gold Card,중간,1500,18,반도체/IT,높음,중국어/영어
22,헝가리,유럽,제조/IT,EU Blue Card,중간,1400,19,IT/제조업,중간,헝가리어/영어
23,폴란드,유럽,제조/IT,National Visa,중간,1300,17,반도체/로봇,중간,폴란드어/영어
0,일본,아시아,제조업/IT,H-1,중간,1200,20,IT/제조업,높음,일본어
6,말레이시아,아시아,제조/서비스,Employment Pass,낮음,900,15,전자/물류,중간,영어
12,중국,아시아,제조/IT,Z Visa,중간,600,20,AI/반도체,중간,중국어
19,러시아,유럽,에너지/자원,Work Visa,중간,600,13,에너지/광산,중간,러시아어
26,멕시코,중남미,제조/자동차,Temporary Resident,낮음,500,10,자동차/가공업,낮음,스페인어
27,브라질,중남미,에너지/농업,Work Visa,낮음,400,7,농업/제약,중간,포르투갈어
8,베트남,아시아,제조/IT,Business Visa,낮음,400,12,IT/소비재,중간,영어/베트남어
7,미얀마,아시아,농업/제조,Business Visa,낮음,300,10,섬유/농업,낮음,영어/현지어
11,인도네시아,아시아,자원/제조,Work Permit,낮음,300,10,자원개발/건설,중간,영어/인도네시아어
14,태국,아시아,관광/제조,Non-Immigrant B,낮음,300,12,관광/요식업,중간,영어/태국어
15,필리핀,아시아,BPO/관광,9(G) Visa,낮음,250,8,BPO/게임,중간,영어/타갈로그어
10,인도,아시아,IT/제조,Employment Visa,낮음,200,10,IT/소프트웨어,중간,영어
13,캄보디아,아시아,농업/관광,E Visa,낮음,200,10,농업/건설,낮음,영어/크메르어

In [ ]:
careerbliss

,Company,Job Title,Overall Rating,Person You Work For,People You Work With,Work Setting,Support You Get,Rewards You Receive,Growth Opportunities,Company Culture,Way You Work
0,Tesla,Senior Investigator,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tesla,Tesla Motors Employee,4.5,5 / 5,5 / 5,4 / 5,4 / 5,5 / 5,5 / 5,5 / 5,4 / 5
2,Tesla,Senior Sales Advisor,4.5,5 / 5,5 / 5,4 / 5,5 / 5,4 / 5,4 / 5,5 / 5,5 / 5
3,Tesla,Tesla Motors Employee,5.0,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5
4,Tesla,Tesla Motors Employee,3.0,4 / 5,3 / 5,3 / 5,4 / 5,3 / 5,3 / 5,3 / 5,3 / 5
...,...,...,...,...,...,...,...,...,...,...,...
1095,Walmart,Assistant Manager,3.5,2 / 5,3 / 5,3 / 5,4 / 5,4 / 5,4 / 5,4 / 5,3 / 5
1096,Walmart,Lead Test Engineer,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1097,Walmart,Walmart Employee,3.5,4 / 5,3 / 5,3 / 5,3 / 5,4 / 5,4 / 5,3 / 5,4 / 5
1098,Walmart,Walmart Employee,3.5,3 / 5,4 / 5,4 / 5,4 / 5,3 / 5,4 / 5,3 / 5,4 / 5
1099,Walmart,Assistant Store Manager,4.5,5 / 5,5 / 5,5 / 5,5 / 5,4 / 5,5 / 5,1 / 5,5 / 5

In [ ]:
careerbliss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Company               1100 non-null   object
 1   Job Title             1100 non-null   object
 2   Overall Rating        1100 non-null   object
 3   Person You Work For   1026 non-null   object
 4   People You Work With  1026 non-null   object
 5   Work Setting          1026 non-null   object
 6   Support You Get       1025 non-null   object
 7   Rewards You Receive   1024 non-null   object
 8   Growth Opportunities  1023 non-null   object
 9   Company Culture       1023 non-null   object
 10  Way You Work          1025 non-null   object
dtypes: object(11)
memory usage: 94.7+ KB

In [ ]:
careerbliss.isna().sum()

Company                  0
Job Title                0
Overall Rating           0
Person You Work For     74
People You Work With    74
Work Setting            74
Support You Get         75
Rewards You Receive     76
Growth Opportunities    77
Company Culture         77
Way You Work            75
dtype: int64

In [ ]:
column_name = 'Overall Rating'
unique_values = df[column_name].unique().tolist()

unique_values

['5.0', '4.5', '3.0', '4.0', '3.5', '2.5', '2.0', '1.0', '1.5', 'Unknown']

In [ ]:
df = careerbliss

# 결측치 처리: NaN을 '0/5'로 대체
df.fillna("0/5", inplace=True)

# 숫자형 변환을 위한 함수 정의
def extract_first_number(value):
    """ '3/5' 같은 형식에서 첫 번째 숫자를 추출하여 변환 """
    return int(float(value.split('/')[0]))

# 변환이 필요한 열들 (정수형으로 변환)
columns_to_convert = [
    "Person You Work For", "People You Work With", "Work Setting", "Support You Get",
    "Rewards You Receive", "Growth Opportunities", "Company Culture", "Way You Work"
]

# 해당 컬럼을 int 형으로 변환
for col in columns_to_convert:
    df[col] = df[col].astype(str).apply(extract_first_number).astype(int)

# 'Overall Rating'만 float으로 변환
df["Overall Rating"] = df["Overall Rating"].replace("Unknown", "0.0").astype(float)
df["Overall Rating"] = df["Overall Rating"].astype(float)

# 그룹화
grouped_df = df.groupby("Company").agg({
    "Job Title": list,  # 리스트로 묶기
    "Overall Rating": "mean",  # 평균 계산 (float)
    "Person You Work For": "mean",  # 평균 계산 (int)
    "People You Work With": "mean",
    "Work Setting": "mean",
    "Support You Get": "mean",
    "Rewards You Receive": "mean",
    "Growth Opportunities": "mean",
    "Company Culture": "mean",
    "Way You Work": "mean"
}).reset_index()

In [ ]:
grouped_df

,Company,Job Title,Overall Rating,Person You Work For,People You Work With,Work Setting,Support You Get,Rewards You Receive,Growth Opportunities,Company Culture,Way You Work
0,Apple,"[RED ZONE Specialist, Technical Specialist, Ap...",4.345,4.21,4.32,4.15,4.16,3.92,3.77,4.11,4.22
1,Costco,"[Programmer Analyst, Merchandiser, Marketing M...",3.765,3.86,4.09,3.66,3.52,3.44,3.42,3.59,3.79
2,Disney,"[Senior Java Developer, Senior Systems and Sto...",4.325,4.63,4.71,4.28,4.47,4.49,4.09,4.56,4.36
3,Google,"[Communications Manager, Mobile Test Engineer,...",4.215,4.07,4.25,4.16,4.07,3.99,3.44,4.09,3.97
4,Mastercard,"[Director of Product, MasterCard Employee, Mas...",3.730,3.96,4.10,3.97,3.64,3.88,3.64,3.64,3.67
5,Netflix,"[Web Developer, Content Acquisition Manager, V...",3.695,3.91,3.91,3.91,3.90,3.98,3.09,3.97,3.73
6,Nvidia,"[NVIDIA Employee, NVIDIA Employee, Wireless Ne...",3.655,3.83,4.00,3.67,3.74,3.61,3.28,3.75,3.76
7,Tesla,"[Senior Investigator, Tesla Motors Employee, S...",4.175,4.24,4.29,3.80,3.93,3.78,3.76,3.70,4.07
8,Toyota,"[Toyota Employee, Toyota Employee, Service Tec...",3.755,4.11,4.25,3.77,3.84,3.71,3.32,3.80,4.05
9,Volkswagen,"[Finance and Insurance Manager, Call Center Re...",3.330,3.69,3.92,3.22,3.36,3.22,2.97,3.35,3.61
10,Walmart,"[Stocker, Walmart Employee, Associate, Cashier...",3.980,4.04,4.21,3.56,3.57,3.53,3.39,3.50,3.94