In [ ]:
import pandas as pd

In [ ]:
careerbliss = pd.read_csv("/content/careerbliss_reviews_fixed (1).csv")

In [ ]:
careerbliss

,Company,Job Title,Overall Rating,Person You Work For,People You Work With,Work Setting,Support You Get,Rewards You Receive,Growth Opportunities,Company Culture,Way You Work
0,Tesla,Equipment Engineering Manager,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tesla,Tesla Motors Employee,4.5,5 / 5,5 / 5,4 / 5,4 / 5,5 / 5,5 / 5,5 / 5,4 / 5
2,Tesla,Senior Sales Advisor,4.5,5 / 5,5 / 5,4 / 5,5 / 5,4 / 5,4 / 5,5 / 5,5 / 5
3,Tesla,Tesla Motors Employee,5.0,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5
4,Tesla,Tesla Motors Employee,3.0,4 / 5,3 / 5,3 / 5,4 / 5,3 / 5,3 / 5,3 / 5,3 / 5
...,...,...,...,...,...,...,...,...,...,...,...
1195,Apple,Technical Support Analyst,3.0,3 / 5,3 / 5,5 / 5,3 / 5,1 / 5,3 / 5,3 / 5,3 / 5
1196,Apple,Specialist,2.0,2 / 5,5 / 5,4 / 5,3 / 5,3 / 5,2 / 5,2 / 5,1 / 5
1197,Apple,Inventory Control Specialist,3.0,1 / 5,5 / 5,3 / 5,5 / 5,4 / 5,2 / 5,2 / 5,2 / 5
1198,Apple,Specialist,3.0,2 / 5,5 / 5,4 / 5,3 / 5,4 / 5,2 / 5,4 / 5,2 / 5
1199,Apple,Help Desk Representative,5.0,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5

In [ ]:
careerbliss["Company"].unique()

array(['Tesla', 'Nvidia', 'Apple'], dtype=object)

## 애플

### 애플모으기

In [ ]:
careerbliss[careerbliss["Company"] == "Apple"]["Job Title"].unique()

array(['Localization and Release Engineer', 'Technical Specialist',
       'Apple Employee', 'Specialist',
       'Product Service Engineering Technician',
       'Senior Front End Developer', 'Technical Product Manager',
       'Dev Ops Engineer', 'Cognizant Engineer', 'Lead DevOps Engineer',
       'Operations Support Specialist', 'Senior SRE',
       'Senior Business Intelligence Analyst', 'Technical Expert',
       'QA Lead', 'Application Support Lead', 'Advisor',
       'Software Engineer', 'Data Analyst', 'QA Engineer',
       'Program Test Manager', 'iOS Phone Support Agent',
       'Senior Technical Advisor', 'SQL Developer', 'Product Specialist',
       'Java Developer', 'Product Design Intern',
       'Senior Software QA Engineer', 'Technical Support Advisor',
       'RED ZONE Specialist', 'Mac Genius',
       'Production Support Specialist', 'Data Engineer', 'IT',
       'Technical Project Manager', 'Genius',
       'Software Development Engineer in Test', 'AppleCare Adviser',
       'Warehouse Operations Manager', 'Relationship Manager',
       'Technical Support Specialist', 'Lead Recruiter',
       'Lead Specialist', 'Technical Advisor',
       'Operations Support Analyst', 'Retail Operations Analyst',
       'DevOps Engineer', 'Technician', 'QA Tester',
       'Technical Program Manager', 'Associate', 'Team Manager', 'Intern',
       'Design Engineer', 'Acoustic Engineering Program Manager',
       'Channel Sales Manager', 'Sales Specialist', 'R&D Intern',
       'QA Agent', 'UI Developer', 'Software QA Engineer',
       'Program Manager', 'Project Management Intern',
       'Creative Media Manager', 'Engineering Program Manager',
       'Machine Learning Intern', 'Data Collection Analyst',
       '2D/3D Image Analyst', 'Graphic Production Artist',
       'IT Infrastructure Manager', 'Senior Advisor',
       'Senior Software Engineer', 'Apple Care Adviser',
       'Machine Learning Engineer', 'Technology Support Analyst',
       'Engineer', 'Software Architect', 'Technical Lead',
       'Development Lead', 'Customer Support Associate',
       'Creative Professional', 'Lead Genius', 'Linguistic Reviewer',
       'Hardware Engineer', 'Wireless Network Engineer',
       'iOS Senior Advisor', 'Project Manager', 'Family Room Specialist',
       'Senior SAP SD Analyst', 'Hadoop Developer', 'Tutor',
       'IT Support Specialist', 'Technical Support Engineer',
       'QA Analyst', 'Technical Support Coach', 'Technical Support Agent',
       'Senior Java Developer', 'Fraud Prevention Specialist',
       'Computer Repair Technician', 'Expert Advisor',
       'Individual Contributor', 'Programmer Analyst',
       'Program Support Advisor', 'Program Developer', 'Business Manager',
       'Systems Administrator', 'Quality Assurance Specialist',
       'Chat Agent', 'Computer Technician',
       'iOS Technical Support Advisor', 'Supply Chain Intern',
       'Lead QA Engineer', 'Campus Representative',
       'Marketing Specialist', 'Build Engineer', 'Retail Sales Associate',
       'IT Project Manager', 'Software Engineering Intern',
       'Creative Specialist', 'Solutions Architect',
       'Application Developer', 'Mac Specialist',
       'Inventory Control Specialist', 'Technical Support Administrator',
       'Technical Support Analyst', 'Help Desk Representative'],
      dtype=object)

In [ ]:
df2 = careerbliss[careerbliss["Company"] == "Apple"]

# df2 데이터프레임을 'df2_output.csv' 파일로 저장
df2.to_csv('df2_output.csv', index=False)

### 매핑

In [ ]:
df2 = careerbliss[careerbliss["Company"] == "Apple"]

# 결측치 처리: NaN을 '0/5'로 대체
df2.fillna("0/5", inplace=True)

# 숫자형 변환을 위한 함수 정의
def extract_first_number(value):
    """ '3/5' 같은 형식에서 첫 번째 숫자를 추출하여 변환 """
    return int(float(value.split('/')[0]))

# 변환이 필요한 열들 (정수형으로 변환)
columns_to_convert = [
    "Person You Work For", "People You Work With", "Work Setting", "Support You Get",
    "Rewards You Receive", "Growth Opportunities", "Company Culture", "Way You Work"
]

# 해당 컬럼을 int 형으로 변환
for col in columns_to_convert:
    df2[col] = df2[col].astype(str).apply(extract_first_number).astype(int)

# 'Overall Rating'만 float으로 변환
df2["Overall Rating"] = df2["Overall Rating"].replace("Unknown", "0.0").astype(float)
df2["Overall Rating"] = df2["Overall Rating"].astype(float)

import pandas as pd

# 그룹 키워드 매핑 정의
job_groups = {
"Engineering": [
"engineer", "engineering", "hardware", "software", "developer", "programmer",
"architect", "qa", "sre", "test", "build", "systems", "devops",
"solutions", "hadoop", "machine learning", "technician"
],
"Product / Design": [
"product", "designer", "ui", "ux", "creative", "graphics", "linguistic",
"visual", "image", "media", "design"
],
"Customer Support": [
"advisor", "applecare", "genius", "support", "associate", "agent", "service",
"chat", "help desk", "customer"
],
"Retail / Sales": [
"retail", "store", "cashier", "sales", "representative", "red zone"
],
"Management / PM": [
"manager", "lead", "team manager", "project manager", "program manager",
"coordinator", "supervisor", "director", "relationship"
],
"Marketing": [
"marketing", "brand", "social", "content", "campaign", "Creative Specialist", "specialist"
],
"Finance / Analyst": [
"finance", "accounting", "analyst", "payroll", "controller", "business intelligence",
"quality assurance", "data analyst", "sql"
],
"HR / People": [
"recruiter", "hr", "human resources", "people", "talent", "campus representative"
],
"Internship": [
"intern", "trainee", "apprentice"
],
"IT / Infrastructure": [
"it", "infrastructure", "technical support", "admin", "network", "systems administrator"
],
"Employee" : [
"Apple Employee"
],
"Expert" : [
"Expert", "Technical Expert"
],
"Others": []
}

# 수정된 버전: 대소문자 구분 제거
def categorize_job_title(title):
    if not isinstance(title, str):
        return "Others"

    title_lower = title.lower()

    for category, keywords in job_groups.items():
        if any(keyword in title_lower for keyword in keywords):
            return category

    return "Others"

# 다시 적용
df2["Job Title2"] = df2["Job Title"].apply(categorize_job_title)

<ipython-input-98-a15ed4e46b93>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.fillna("0/5", inplace=True)
<ipython-input-98-a15ed4e46b93>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col] = df2[col].astype(str).apply(extract_first_number).astype(int)
<ipython-input-98-a15ed4e46b93>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col] = df2[col].astype(str).apply(extract_first_number).astype(int)
<ipython-input-98-a15ed4e46b93>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col] = df2[col].astype(str).apply(extract_first_number).astype(int)
<ipython-input-98-a15ed4e46b93>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col] = df2[col].astype(str).apply(extract_first_number).astype(int)
<ipython-input-98-a15ed4e46b93>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col] = df2[col].astype(str).apply(extract_first_number).astype(int)
<ipython-input-98-a15ed4e46b93>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col] = df2[col].astype(str).apply(extract_first_number).astype(int)
<ipython-input-98-a15ed4e46b93>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col] = df2[col].astype(str).apply(extract_first_number).astype(int)
<ipython-input-98-a15ed4e46b93>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col] = df2[col].astype(str).apply(extract_first_number).astype(int)
<ipython-input-98-a15ed4e46b93>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Overall Rating"] = df2["Overall Rating"].replace("Unknown", "0.0").astype(float)
<ipython-input-98-a15ed4e46b93>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Overall Rating"] = df2["Overall Rating"].astype(float)
<ipython-input-98-a15ed4e46b93>:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Job Title2"] = df2["Job Title"].apply(categorize_job_title)

In [ ]:
df2["Job Title2"].value_counts()

Job Title2
Others                 191
Engineering             66
Customer Support        47
Marketing               39
Management / PM         18
Product / Design        15
Retail / Sales          10
Finance / Analyst        9
Internship               4
IT / Infrastructure      1
Name: count, dtype: int64

In [ ]:
# 'Job Title2' 열에서 'Others'인 행을 필터링하고, 해당 'Job Title' 값을 추출
job_title_others = df2[df2["Job Title2"] == "Others"]["Job Title"]

# 각 'Job Title' 값들의 빈도를 계산
job_title_counts = job_title_others.value_counts()

job_title_counts

Job Title
Apple Employee            182
Technical Expert            6
Apple Care Adviser          1
Tutor                       1
Individual Contributor      1
Name: count, dtype: int64

### 매핑 수정

In [ ]:
# Job Title2가 'Others'인 경우, 'apple employee'와 'technical expert'를 각각 'employee'와 'expert'로 수정
df2.loc[df2['Job Title2'] == 'Others', 'Job Title2'] = df2.loc[df2['Job Title2'] == 'Others', 'Job Title'].apply(
    lambda x: 'Employee' if 'apple employee' in str(x).lower() else ('Expert' if 'technical expert' in str(x).lower() else 'Others')
)

In [ ]:
df2["Job Title2"].value_counts()

Job Title2
Employee               182
Engineering             66
Customer Support        47
Marketing               39
Management / PM         18
Product / Design        15
Retail / Sales          10
Finance / Analyst        9
Expert                   6
Internship               4
Others                   3
IT / Infrastructure      1
Name: count, dtype: int64

In [ ]:
grouped_df2 = df2.groupby(["Company", "Job Title2"]).agg({
    "Overall Rating": "mean",  # 평균 계산 (float)
    "Person You Work For": "mean",  # 평균 계산 (int)
    "People You Work With": "mean",
    "Work Setting": "mean",
    "Support You Get": "mean",
    "Rewards You Receive": "mean",
    "Growth Opportunities": "mean",
    "Company Culture": "mean",
    "Way You Work": "mean"
}).reset_index()

In [ ]:
grouped_df2

,Company,Job Title2,Overall Rating,Person You Work For,People You Work With,Work Setting,Support You Get,Rewards You Receive,Growth Opportunities,Company Culture,Way You Work
0,Apple,Customer Support,3.893617,3.638298,3.957447,3.510638,3.702128,3.127660,2.851064,3.553191,3.361702
1,Apple,Employee,4.052198,4.241758,4.516484,4.016484,4.258242,3.895604,3.609890,4.027473,4.192308
2,Apple,Engineering,4.340909,3.818182,4.075758,3.742424,3.863636,3.681818,3.454545,3.757576,3.878788
3,Apple,Expert,4.333333,4.666667,5.000000,4.833333,5.000000,4.333333,4.666667,4.666667,4.666667
4,Apple,Finance / Analyst,4.500000,2.777778,2.777778,2.333333,2.555556,2.555556,2.222222,2.444444,2.444444
5,Apple,IT / Infrastructure,4.000000,5.000000,4.000000,2.000000,5.000000,5.000000,2.000000,3.000000,5.000000
6,Apple,Internship,4.625000,4.500000,4.500000,5.000000,4.750000,4.750000,4.250000,4.500000,4.500000
7,Apple,Management / PM,3.972222,3.722222,4.833333,4.111111,4.000000,3.777778,3.666667,3.777778,4.111111
8,Apple,Marketing,3.948718,3.564103,4.128205,3.794872,3.794872,3.410256,3.025641,3.717949,3.564103
9,Apple,Others,4.166667,4.666667,4.666667,4.666667,5.000000,3.333333,3.333333,4.000000,4.333333
10,Apple,Product / Design,4.266667,4.533333,4.733333,4.466667,4.733333,4.000000,4.000000,4.000000,4.733333
11,Apple,Retail / Sales,4.650000,2.400000,3.000000,2.800000,2.600000,2.400000,2.100000,2.900000,3.000000

ex. apple은 엔지니어의 만족도가 좋다. sales의 만족도는 낮다. 그 이유는 성장가능성과 페이 때문인듯이다. 라고 할 수 있단말이지 근데 엔지니어는 47명 sales는 19명 밖에 안된단 말이야. 너무 편향된거일까봐.

- 이떄 GPT의 충고\

가능: "Apple에서 Engineering 직군의 평균 만족도는 가장 높았으며, 표본 수(47건)도 상대적으로 충분하여 신뢰도 있는 분석 가능성 있음."

주의: "Sales 직군의 표본 수(19건)는 분석 시 신중한 해석이 필요함. 극단값이나 특정 인원의 영향이 클 수 있음."

지양: "Design 직무의 평균 만족도가 낮았다 → (표본이 3개이므로 통계적 해석 불가)"

## 참고자료 - 직무 리스트(엔비디아, 테슬라)

In [ ]:
# 참고
careerbliss[careerbliss["Company"] == "Tesla"]["Job Title"].unique()

array(['Equipment Engineering Manager', 'Tesla Motors Employee',
       'Senior Sales Advisor', 'Packaging Engineering Intern',
       'Senior Manufacturing Engineer', 'Recruiting Coordinator',
       '.NET Developer', 'Management Intern', 'Lead Installer',
       'Equipment Maintenance Technician', 'Supervisor',
       'Business Development Intern', 'Senior Investigator',
       'Mechanical Design Engineering Intern', 'Maintenance Supervisor',
       'Shift Lead', 'Data Specialist', 'QA Specialist', 'Installer',
       'Production Control Supervisor', 'Production Technician',
       'Technical Writer', 'Program Manager', 'Machine Operator',
       'Senior Manager', 'Security Intern', 'Revenue Accountant',
       'Production Associate', 'Surveyor', 'Test Engineering Intern',
       'Production Supervisor', 'Maintenance Technician',
       'Materials Handler', 'Manufacturing Engineer',
       'Production Engineering Supervisor', 'Design Lead',
       'Mechanical Engineering Intern', 'Mechanical Engineer',
       'Senior Controls Technician', 'Senior Mechanical Design Engineer',
       'Sound Engineer', 'Remanufacturing Engineering Intern',
       'Operations Supervisor', 'Inside Sales Representative',
       'Engineering Support Analyst', 'Industrial Engineering Intern',
       'Network Operations Intern', 'Senior Software Engineer',
       'Energy Consultant', 'Delivery Operations Manager',
       'Senior Regional Security Manager', 'Mobile Developer',
       'Data Migration Specialist', 'Manufacturing Project Manager',
       'QA Engineer', 'Manager', 'Manufacturing Manager',
       'Senior Firmware Engineer', 'auto technician',
       'Project Management Intern', 'Manufacturing Equipment Engineer',
       'System Design Engineer', 'Quality Engineering Intern',
       'Quality Engineering Technician'], dtype=object)

In [ ]:
#참고
careerbliss[careerbliss["Company"] == "Nvidia"]["Job Title"].unique()

array(['NVIDIA Employee', 'Wireless Network Administrator',
       'Performance Engineer', 'Hardware Systems Architect',
       'Thermal Intern', 'ASIC Design Engineer', 'Software Test Lead',
       'Software Engineering Intern', 'Senior Software Engineer',
       'Systems Test Engineer', 'Senior Test Engineer',
       'Mobile QA Engineer', 'Lead Software QA Engineer',
       'Hardware QA Engineer', 'Software QA Manager',
       'Software Developer', 'Electrical Tester',
       'Member of Technical Staff', 'Software QA Engineer',
       'Automation Engineer', 'Senior Hardware Engineer',
       'Software Engineer', 'Senior Engineer', 'National Account Manager',
       'Hardware Engineer', 'Senior Product Engineer',
       'Senior Factory Planner', 'Software Quality Assurance Engineer',
       'Summer Intern', 'Systems Support Engineer',
       'Embedded Software Engineer', 'Senior Systems Engineer'],
      dtype=object)

# 날짜 위치 포함 데이터 확인

In [ ]:
plus = pd.read_csv("/content/careerbliss_location.csv")

In [ ]:
plus

,Company,Job Title,Overall Rating,Posted Date,Location,Person You Work For,People You Work With,Work Setting,Support You Get,Rewards You Receive,Growth Opportunities,Company Culture,Way You Work
0,Tesla,Senior Investigator,5.0,5 years ago,"Sparks, NV",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tesla,Tesla Motors Employee,4.5,Unknown,Unknown,5 / 5,5 / 5,4 / 5,4 / 5,5 / 5,5 / 5,5 / 5,4 / 5
2,Tesla,Senior Sales Advisor,4.5,Unknown,Unknown,5 / 5,5 / 5,4 / 5,5 / 5,4 / 5,4 / 5,5 / 5,5 / 5
3,Tesla,Tesla Motors Employee,5.0,Unknown,Unknown,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5
4,Tesla,Tesla Motors Employee,3.0,Unknown,Unknown,4 / 5,3 / 5,3 / 5,4 / 5,3 / 5,3 / 5,3 / 5,3 / 5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,Apple,Technical Support Analyst,3.0,Unknown,Unknown,3 / 5,3 / 5,5 / 5,3 / 5,1 / 5,3 / 5,3 / 5,3 / 5
1196,Apple,Specialist,2.0,Unknown,Unknown,2 / 5,5 / 5,4 / 5,3 / 5,3 / 5,2 / 5,2 / 5,1 / 5
1197,Apple,Inventory Control Specialist,3.0,Unknown,Unknown,1 / 5,5 / 5,3 / 5,5 / 5,4 / 5,2 / 5,2 / 5,2 / 5
1198,Apple,Specialist,3.0,Unknown,Unknown,2 / 5,5 / 5,4 / 5,3 / 5,4 / 5,2 / 5,4 / 5,2 / 5
1199,Apple,Help Desk Representative,5.0,Unknown,Unknown,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5

# 최종 데이터셋 제작

In [ ]:
df = pd.read_csv("/content/grouped_rating_summary.csv")

In [ ]:
df

           role_grouped    rating
0      Customer Support  3.839286
1              Employee  4.052198
2           Engineering  4.168269
3                Expert  3.888889
4     Finance / Analyst  3.875000
5   IT / Infrastructure  4.142857
6            Internship  4.214286
7       Management / PM  4.261364
8             Marketing  4.500000
9                Others  3.866071
10     Product / Design  4.140097
11       Retail / Sales  4.578947

In [ ]:
# 여러 값을 동시에 바꾸는 코드
df['role_grouped'] = df['role_grouped'].replace({'Employee': 'employee	', 'Expert': 'expert'})

In [ ]:
DATA = pd.merge(grouped_df2,review, left_on='Job Title2', right_on='role_grouped', how='outer')

In [ ]:
DATA

,Company,Job Title2,Overall Rating,Person You Work For,People You Work With,Work Setting,Support You Get,Rewards You Receive,Growth Opportunities,Company Culture,Way You Work,role_grouped,rating
0,Apple,Customer Support,3.893617,3.638298,3.957447,3.510638,3.702128,3.127660,2.851064,3.553191,3.361702,Customer Support,3.839286
1,Apple,Employee,4.052198,4.241758,4.516484,4.016484,4.258242,3.895604,3.609890,4.027473,4.192308,Employee,4.052198
2,Apple,Engineering,4.340909,3.818182,4.075758,3.742424,3.863636,3.681818,3.454545,3.757576,3.878788,Engineering,4.168269
3,Apple,Expert,4.333333,4.666667,5.000000,4.833333,5.000000,4.333333,4.666667,4.666667,4.666667,Expert,3.888889
4,Apple,Finance / Analyst,4.500000,2.777778,2.777778,2.333333,2.555556,2.555556,2.222222,2.444444,2.444444,Finance / Analyst,3.875000
5,Apple,IT / Infrastructure,4.000000,5.000000,4.000000,2.000000,5.000000,5.000000,2.000000,3.000000,5.000000,IT / Infrastructure,4.142857
6,Apple,Internship,4.625000,4.500000,4.500000,5.000000,4.750000,4.750000,4.250000,4.500000,4.500000,Internship,4.214286
7,Apple,Management / PM,3.972222,3.722222,4.833333,4.111111,4.000000,3.777778,3.666667,3.777778,4.111111,Management / PM,4.261364
8,Apple,Marketing,3.948718,3.564103,4.128205,3.794872,3.794872,3.410256,3.025641,3.717949,3.564103,Marketing,4.500000
9,Apple,Others,4.166667,4.666667,4.666667,4.666667,5.000000,3.333333,3.333333,4.000000,4.333333,Others,3.866071
10,Apple,Product / Design,4.266667,4.533333,4.733333,4.466667,4.733333,4.000000,4.000000,4.000000,4.733333,Product / Design,4.140097
11,Apple,Retail / Sales,4.650000,2.400000,3.000000,2.800000,2.600000,2.400000,2.100000,2.900000,3.000000,Retail / Sales,4.578947

In [ ]:
DATA = DATA.drop(columns=['role_grouped'])


DATA = DATA.rename(columns={'Job Title2': '직무'})

DATA['전체 평점'] = DATA[['Overall Rating', 'rating']].mean(axis=1)

In [ ]:
DATA

,Company,직무,Overall Rating,Person You Work For,People You Work With,Work Setting,Support You Get,Rewards You Receive,Growth Opportunities,Company Culture,Way You Work,rating,전체 평점
0,Apple,Customer Support,3.893617,3.638298,3.957447,3.510638,3.702128,3.127660,2.851064,3.553191,3.361702,3.839286,3.866451
1,Apple,Employee,4.052198,4.241758,4.516484,4.016484,4.258242,3.895604,3.609890,4.027473,4.192308,4.052198,4.052198
2,Apple,Engineering,4.340909,3.818182,4.075758,3.742424,3.863636,3.681818,3.454545,3.757576,3.878788,4.168269,4.254589
3,Apple,Expert,4.333333,4.666667,5.000000,4.833333,5.000000,4.333333,4.666667,4.666667,4.666667,3.888889,4.111111
4,Apple,Finance / Analyst,4.500000,2.777778,2.777778,2.333333,2.555556,2.555556,2.222222,2.444444,2.444444,3.875000,4.187500
5,Apple,IT / Infrastructure,4.000000,5.000000,4.000000,2.000000,5.000000,5.000000,2.000000,3.000000,5.000000,4.142857,4.071429
6,Apple,Internship,4.625000,4.500000,4.500000,5.000000,4.750000,4.750000,4.250000,4.500000,4.500000,4.214286,4.419643
7,Apple,Management / PM,3.972222,3.722222,4.833333,4.111111,4.000000,3.777778,3.666667,3.777778,4.111111,4.261364,4.116793
8,Apple,Marketing,3.948718,3.564103,4.128205,3.794872,3.794872,3.410256,3.025641,3.717949,3.564103,4.500000,4.224359
9,Apple,Others,4.166667,4.666667,4.666667,4.666667,5.000000,3.333333,3.333333,4.000000,4.333333,3.866071,4.016369
10,Apple,Product / Design,4.266667,4.533333,4.733333,4.466667,4.733333,4.000000,4.000000,4.000000,4.733333,4.140097,4.203382
11,Apple,Retail / Sales,4.650000,2.400000,3.000000,2.800000,2.600000,2.400000,2.100000,2.900000,3.000000,4.578947,4.614474

In [ ]:
DATA = DATA.rename(columns={'Overall Rating': '리뷰2 전체평점', 'rating': '리뷰1 전체 평점', 'Person You Work For': '경영진', 'People You Work With':'동료', 'Work Setting':'환경',
                            'Support You Get':'복지','Rewards You Receive':'임금','Growth Opportunities':'성장 가능성','Company Culture':'기업문화','Way You Work':'일처리방식'})

In [ ]:
DATA

,Company,직무,리뷰2 전체평점,경영진,동료,환경,복지,임금,성장 가능성,기업문화,일처리방식,리뷰1 전체 평점,전체 평점
0,Apple,Customer Support,3.893617,3.638298,3.957447,3.510638,3.702128,3.127660,2.851064,3.553191,3.361702,3.839286,3.866451
1,Apple,Employee,4.052198,4.241758,4.516484,4.016484,4.258242,3.895604,3.609890,4.027473,4.192308,4.052198,4.052198
2,Apple,Engineering,4.340909,3.818182,4.075758,3.742424,3.863636,3.681818,3.454545,3.757576,3.878788,4.168269,4.254589
3,Apple,Expert,4.333333,4.666667,5.000000,4.833333,5.000000,4.333333,4.666667,4.666667,4.666667,3.888889,4.111111
4,Apple,Finance / Analyst,4.500000,2.777778,2.777778,2.333333,2.555556,2.555556,2.222222,2.444444,2.444444,3.875000,4.187500
5,Apple,IT / Infrastructure,4.000000,5.000000,4.000000,2.000000,5.000000,5.000000,2.000000,3.000000,5.000000,4.142857,4.071429
6,Apple,Internship,4.625000,4.500000,4.500000,5.000000,4.750000,4.750000,4.250000,4.500000,4.500000,4.214286,4.419643
7,Apple,Management / PM,3.972222,3.722222,4.833333,4.111111,4.000000,3.777778,3.666667,3.777778,4.111111,4.261364,4.116793
8,Apple,Marketing,3.948718,3.564103,4.128205,3.794872,3.794872,3.410256,3.025641,3.717949,3.564103,4.500000,4.224359
9,Apple,Others,4.166667,4.666667,4.666667,4.666667,5.000000,3.333333,3.333333,4.000000,4.333333,3.866071,4.016369
10,Apple,Product / Design,4.266667,4.533333,4.733333,4.466667,4.733333,4.000000,4.000000,4.000000,4.733333,4.140097,4.203382
11,Apple,Retail / Sales,4.650000,2.400000,3.000000,2.800000,2.600000,2.400000,2.100000,2.900000,3.000000,4.578947,4.614474

In [ ]:
DATA.to_csv('최종데이터1차.csv', index=False)

## 날짜 다시

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("careerbliss_reviews.csv")

In [ ]:
data

,Company,Job Title,Overall Rating,Posted Date,Person You Work For,People You Work With,Work Setting,Support You Get,Rewards You Receive,Growth Opportunities,Company Culture,Way You Work
0,Tesla,Senior Sales Advisor,4.5,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tesla,Tesla Motors Employee,4.5,Unknown,5 / 5,5 / 5,4 / 5,4 / 5,5 / 5,5 / 5,5 / 5,4 / 5
2,Tesla,Senior Sales Advisor,4.5,Unknown,5 / 5,5 / 5,4 / 5,5 / 5,4 / 5,4 / 5,5 / 5,5 / 5
3,Tesla,Tesla Motors Employee,5.0,Unknown,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5
4,Tesla,Tesla Motors Employee,3.0,Unknown,4 / 5,3 / 5,3 / 5,4 / 5,3 / 5,3 / 5,3 / 5,3 / 5
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,Apple,Technical Support Analyst,3.0,Unknown,3 / 5,3 / 5,5 / 5,3 / 5,1 / 5,3 / 5,3 / 5,3 / 5
1196,Apple,Specialist,2.0,Unknown,2 / 5,5 / 5,4 / 5,3 / 5,3 / 5,2 / 5,2 / 5,1 / 5
1197,Apple,Inventory Control Specialist,3.0,Unknown,1 / 5,5 / 5,3 / 5,5 / 5,4 / 5,2 / 5,2 / 5,2 / 5
1198,Apple,Specialist,3.0,Unknown,2 / 5,5 / 5,4 / 5,3 / 5,4 / 5,2 / 5,4 / 5,2 / 5
1199,Apple,Help Desk Representative,5.0,Unknown,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5

## 지역 다시

In [ ]:
dd = pd.read_csv("/content/careerbliss_reviews_with_location (2).csv")

In [ ]:
dd

,Company,Job Title,Overall Rating,Location,Person You Work For,People You Work With,Work Setting,Support You Get,Rewards You Receive,Growth Opportunities,Company Culture,Way You Work
0,Tesla,Senior Sales Advisor,4.5,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tesla,Tesla Motors Employee,4.5,"Sparks, NV",5 / 5,5 / 5,4 / 5,4 / 5,5 / 5,5 / 5,5 / 5,4 / 5
2,Tesla,Senior Sales Advisor,4.5,"Glendale, CA",5 / 5,5 / 5,4 / 5,5 / 5,4 / 5,4 / 5,5 / 5,5 / 5
3,Tesla,Tesla Motors Employee,5.0,"Fremont, CA",5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5
4,Tesla,Tesla Motors Employee,3.0,"Fremont, CA",4 / 5,3 / 5,3 / 5,4 / 5,3 / 5,3 / 5,3 / 5,3 / 5
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,Apple,Technical Support Analyst,3.0,"San Antonio, TX",3 / 5,3 / 5,5 / 5,3 / 5,1 / 5,3 / 5,3 / 5,3 / 5
1196,Apple,Specialist,2.0,"San Francisco, CA",2 / 5,5 / 5,4 / 5,3 / 5,3 / 5,2 / 5,2 / 5,1 / 5
1197,Apple,Inventory Control Specialist,3.0,"Frisco, TX",1 / 5,5 / 5,3 / 5,5 / 5,4 / 5,2 / 5,2 / 5,2 / 5
1198,Apple,Specialist,3.0,"Boulder, CO",2 / 5,5 / 5,4 / 5,3 / 5,4 / 5,2 / 5,4 / 5,2 / 5
1199,Apple,Help Desk Representative,5.0,"Cypress, TX",5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5,5 / 5

In [ ]:
dd["Location"].unique()

array(['Unknown', 'Sparks, NV', 'Glendale, CA', 'Fremont, CA',
       'San Jose, CA', 'Buffalo, NY', 'Mount Kisco, NY',
       'Los Angeles, CA', 'San Francisco, CA', 'Milpitas, CA',
       'Palo Alto, CA', 'Reno, NV', 'San Mateo, CA', 'Las Vegas, NV',
       'West Lafayette, IN', 'Santa Clara, CA', 'Parker, CO',
       'Orlando, FL', 'Mission Viejo, CA', 'Fremont, NE', 'Livermore, CA',
       'Rocklin, CA', 'Santa Ana, CA', 'Mountain View, CA', 'Draper, UT',
       'Costa Mesa, CA', 'Indianapolis, IN', 'Palo, IA',
       'Castro Valley, CA', 'San Carlos, AZ', 'Austin, TX',
       'Buena Park, CA', 'Fresno, CA', 'Salt Lake City, UT', 'Santa, ID',
       'Beaverton, OR', 'Ogden, UT', 'Dallas, TX', 'Sunnyvale, CA',
       'Cupertino, CA', 'Denver, CO', 'Santa Barbara, CA',
       'Jacksonville, FL', 'New York City, NY', 'Elk Grove, CA',
       'Raleigh, NC', 'California City, CA', 'South Windsor, CT',
       'San Diego, CA', 'Talladega, AL', 'White Plains, NY',
       'Modesto, CA', 'Charlotte, NC', 'Buford, GA',
       'Rancho Cucamonga, CA', 'McKeesport, PA', 'Chicago, IL',
       'Chandler, AZ', 'McLean, VA', 'Northville, MI', 'Scottsdale, AZ',
       'Napoleonville, LA', 'Gilbert, AZ', 'Toronto, OH',
       'Short Hills, NJ', 'Columbia, MD', 'London, ON', 'Columbus, OH',
       'Fort Lauderdale, FL', 'Houston, TX', 'Culver City, CA',
       'Pittsburgh, PA', 'Boulder, CO', 'Lake Grove, NY',
       'Cincinnati, OH', 'South Portland, ME', 'Baton Rouge, LA',
       'Portland, OR', 'Redwood City, CA', 'Manhattan Beach, CA',
       'Sarasota, FL', 'North Lauderdale, FL', 'Chesterfield, VA',
       'Braintree, MA', 'Tuckahoe, NY', 'Tacoma, WA', 'Ballwin, MO',
       'Irvine, CA', 'Atlanta, GA', 'Rancho Cordova, CA',
       'Marlborough, MA', 'Remote, OR', 'Rowland Heights, CA',
       'Escondido, CA', 'Brea, CA', 'Cerritos, CA', 'Greece, NY',
       'San Leandro, CA', 'Pleasanton, CA', 'Portland, ME',
       'Sacramento, CA', 'Hattiesburg, MS', 'Durham, NC',
       'Santa Monica, CA', 'Woodcliff Lake, NJ', 'Arlington, VA',
       'Temecula, CA', 'Natick, MA', 'Newport Beach, CA', 'Westlake, OH',
       'Grand Rapids, MI', 'Milwaukee, WI', 'Tukwila, WA', 'Norman, OK',
       'Atco, NJ', 'Dresden, TN', 'Aventura, FL', 'Dedham, MA',
       'Freehold, NJ', 'Nashua, NH', 'Rome, GA', 'Towson, MD',
       'Rockaway, NJ', 'Lyndhurst, OH', 'Alpharetta, GA', 'Hillsboro, OR',
       'Reston, VA', 'Lancaster, NY', 'Ireland, WV', 'Lynnwood, WA',
       'Baltimore, MD', 'Belfast, NY', 'Miami, FL', 'Bellevue, WA',
       'Hyannis, MA', 'San Antonio, TX', 'Frisco, TX', 'Cypress, TX'],
      dtype=object)